version: '2'

services:

  sentence.splitter:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/nltk_base
    networks:
      - primary
    command: python /opt/scripts/sentence_splitter.py
      
  word.tokenizer:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/nltk_base
    networks:
      - primary
    command: python /opt/scripts/word_tokenizer.py

  pos.tagger:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/nltk_base
    networks:
      - primary
    command: python /opt/scripts/pos_tagger.py
  
  ne.chunker:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/nltk_base
    networks:
      - primary
    command: python /opt/scripts/ne_chunker.py
    
  ne.annotator:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/nltk_base
    networks:
      - primary
    command: python /opt/scripts/ne_annotator.py
    ports:
      - 9090:9090
    depends_on:
      - sentence.splitter
      - word.tokenizer
      - pos.tagger
      - ne.chunker

  web:
    build:
      context: .
      dockerfile: Dockerfile.nltk_base
    image: hltcoe/web
    networks:
      - primary
    command: python /opt/scripts/run_ui.py
    ports:
      - 8080:8080
    depends_on:
      - ne.annotator
      
networks:
  primary:
